-- ============================================
-- FULL SETUP SQL - E-Learning SMA
-- ============================================

-- 1. HAPUS TABEL LAMA (jika ada) - agar tidak konflik
DROP TABLE IF EXISTS chats CASCADE;
DROP TABLE IF EXISTS attendances CASCADE;
DROP TABLE IF EXISTS submissions CASCADE;
DROP TABLE IF EXISTS assignments CASCADE;
DROP TABLE IF EXISTS materials CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- ============================================
-- 2. BUAT TABEL
-- ============================================

CREATE TABLE profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text check (role in ('student', 'teacher', 'admin')),
  class_id text,
  avatar_url text
);

CREATE TABLE classes (
  id text primary key,
  name text
);

CREATE TABLE subjects (
  id bigint generated by default as identity primary key,
  name text,
  teacher_id uuid references profiles(id),
  class_id text references classes(id),
  schedule_day text,
  schedule_time text
);

CREATE TABLE materials (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id),
  title text,
  type text,
  content_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

CREATE TABLE assignments (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id),
  title text,
  description text,
  deadline timestamp with time zone
);

CREATE TABLE submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint references assignments(id),
  student_id uuid references profiles(id),
  file_url text,
  grade int,
  feedback text,
  submitted_at timestamp with time zone
);

CREATE TABLE attendances (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id),
  student_id uuid references profiles(id),
  date date,
  status text
);

CREATE TABLE chats (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id),
  sender_id uuid references profiles(id),
  message text,
  sent_at timestamp with time zone default timezone('utc'::text, now())
);

-- ============================================
-- 3. TRIGGER OTOMATIS BUAT PROFILE SAAT SIGNUP
-- ============================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', 'User'),
    COALESCE(new.raw_user_meta_data->>'role', 'student')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ============================================
-- 4. AKTIFKAN RLS
-- ============================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendances ENABLE ROW LEVEL SECURITY;
ALTER TABLE chats ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 5. RLS POLICIES
-- ============================================

-- Profiles
CREATE POLICY "profiles_select" ON profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "profiles_insert" ON profiles FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "profiles_update" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id);

-- Classes
CREATE POLICY "classes_select" ON classes FOR SELECT TO authenticated USING (true);
CREATE POLICY "classes_all" ON classes FOR ALL TO authenticated USING (true);

-- Subjects
CREATE POLICY "subjects_select" ON subjects FOR SELECT TO authenticated USING (true);
CREATE POLICY "subjects_all" ON subjects FOR ALL TO authenticated USING (true);

-- Materials
CREATE POLICY "materials_select" ON materials FOR SELECT TO authenticated USING (true);
CREATE POLICY "materials_all" ON materials FOR ALL TO authenticated USING (true);

-- Assignments
CREATE POLICY "assignments_select" ON assignments FOR SELECT TO authenticated USING (true);
CREATE POLICY "assignments_all" ON assignments FOR ALL TO authenticated USING (true);

-- Submissions
CREATE POLICY "submissions_select" ON submissions FOR SELECT TO authenticated USING (true);
CREATE POLICY "submissions_all" ON submissions FOR ALL TO authenticated USING (true);

-- Attendances
CREATE POLICY "attendances_select" ON attendances FOR SELECT TO authenticated USING (true);
CREATE POLICY "attendances_all" ON attendances FOR ALL TO authenticated USING (true);

-- Chats
CREATE POLICY "chats_select" ON chats FOR SELECT TO authenticated USING (true);
CREATE POLICY "chats_all" ON chats FOR ALL TO authenticated USING (true);

-- ============================================
-- 6. GRANT PERMISSIONS
-- ============================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated;

-- ============================================
-- 7. DATA SAMPLE
-- ============================================

-- Kelas
INSERT INTO classes (id, name) VALUES
  ('X-IPA-1',   'X IPA 1'),
  ('X-IPS-1',   'X IPS 1'),
  ('XI-IPA-1',  'XI IPA 1'),
  ('XI-IPS-1',  'XI IPS 1'),
  ('XII-IPA-1', 'XII IPA 1'),
  ('XII-IPS-1', 'XII IPS 1')
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- 8. SET ADMIN - rianhidayat243@gmail.com
-- ============================================

-- Jika user sudah ada di auth, update profilenya
UPDATE public.profiles
SET
  role      = 'admin',
  full_name = 'Rian Hidayat',
  email     = 'rianhidayat243@gmail.com'
WHERE email = 'rianhidayat243@gmail.com';

-- Verifikasi
SELECT id, email, full_name, role FROM profiles
WHERE email = 'rianhidayat243@gmail.com';